import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import CustomCursor from "@/components/CustomCursor";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ModeToggle } from "@/components/Toggle";
import Footer from "@/components/Footer";
import ContactLocations from "@/components/Contact";
import PageLoader from "@/components/PageLoader";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Consult with BzAnalytics",
  description: "Generated by create next app",
  icons: {
    icon: "/bz.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakartaSans.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModeToggle />
          <PageLoader>
            <Header />
            <CustomCursor />
            {children}
            <ContactLocations />
            <Footer />
          </PageLoader>
        </ThemeProvider>
      </body>
    </html>
  );
}
